name: Günlük Ürün Güncelle

on:
  schedule:
    - cron: '0 5 * * *'  # Her gün sabah 05:00 UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Repo'yu klonla
      uses: actions/checkout@v3

    - name: Python kurulumu
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Paketleri yükle
      run: pip install requests

    - name: HTML üret
      run: python generate_html.py

    - name: Değişiklikleri commit et ve pushla
      run: |
        git config user.name "github-actions"
        git config user.email "actions@github.com"
        git add products.html
        git commit -m "products.html otomatik güncellendi" || echo "Değişiklik yok"
        git push
